# Generated by Django 4.1.9 on 2024-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_contact_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_me',
            name='icon',
            field=models.ImageField(blank=True, upload_to='contact_image/'),
        ),
    ]
