# Generated by Django 3.2 on 2025-01-07 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_contact_me_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_me',
            name='user_name',
        ),
        migrations.AddField(
            model_name='contact_me',
            name='User_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_me',
            name='icon',
            field=models.ImageField(blank=True, upload_to='contact_images/'),
        ),
    ]
