# Generated by Django 3.2 on 2025-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='project_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact_me',
        ),
    ]
